-- revised by oleh5230, 17.04.25
-- Last edit: 07.07.25
-- credits: CustomBeerFairy, ForserX

local debug = false

local jump_sound, land_sound
local volume = 0.5
local enabled = true
local ice_patch = false
local grass_patch = false

local servo_volume = 0.5
local servo_enabled = true
local exo_classes = {
    ["outfit_exo_proto"]    = "light",
    ["outfit_exo"]          = "medium",
    ["outfit_exo_nosorog"]  = "medium",
}

function actor_on_jump()
    if not enabled then return end
    local outfit = oleh_sound_utils.get_outfit_params() or {id = nil, class = "default", weight = 10}

    local material = available_materials[get_material()]
    if not material then return false end
    jump_sound = sound_object("jump\\jump_" .. material .. math.random(3))
    jump_sound:play(db.actor, 0, sound_object.s2d)
    jump_sound.volume = volume

    -- play gear rattle
    if footstep_sounds and footstep_sounds.play_backpack_rattle then
        footstep_sounds.play_backpack_rattle(outfit, 1)
        footstep_sounds.play_gear_rattle(outfit, 2)
        footstep_sounds.play_cloth_sound(outfit, 2)
    end

    -- play exo servo sounds
    if servo_enabled and exo_classes[outfit.class] then
        local sound = sound_object("exo-gear-walk-jump-land\\servo_exo_jump_" .. exo_classes[outfit.class])
        sound:play(db.actor, 0, sound_object.s2d)
        sound.volume = servo_volume
    end
end

function actor_on_land(landing_speed)
    if not enabled then return end
    local outfit = oleh_sound_utils.get_outfit_params() or {id = nil, class = "default", weight = 10}

    -- hack for speed set to 0 by fake geometry
    if landing_speed == 0 then landing_speed = 6.66 end
    print_dbg("landing_speed: %s", landing_speed)
	if landing_speed > 2 then
        local material = available_materials[get_material(true)]
        if not material then return false end
        land_sound = sound_object("landing\\landing_" .. material .. math.random(3))
        land_sound:play(db.actor, 0, sound_object.s2d)
        land_sound.volume = volume * (landing_speed / 5)
    end

    -- play gear rattle
    if footstep_sounds and footstep_sounds.play_backpack_rattle then
        footstep_sounds.play_backpack_rattle(outfit, landing_speed)
        footstep_sounds.play_gear_rattle(outfit, landing_speed)
        footstep_sounds.play_cloth_sound(outfit, 1)
    end

    -- play exo servo sounds
    if servo_enabled and exo_classes[outfit.class] then
        local sound = sound_object("exo-gear-walk-jump-land\\servo_exo_land_" .. exo_classes[outfit.class])
        sound:play(db.actor, 0, sound_object.s2d)
        sound.volume = servo_volume
    end
end

local function get_highest_value(tbl)
    local max_key
    local max_value = 0
    for k,v in pairs(tbl) do
        if v and v > max_value then
            max_value = v
            max_key = k
        end
    end
    return max_key
end

local function ray_cast(pos, dir, range, visualize)
    local ray = demonized_geometry_ray.geometry_ray({
        ray_range = range or 0.5,
        flags = 3, --1 + 2 + 4 + 8,
        ignore_object = db.actor,
        visualize = debug and visualize or false,
    })
    return ray:get(pos, dir).result.material_name
end

-- vertical x-shaped raycast pattern;
-- radius is slightly smaller than player collision box (bubble?);
-- when editing y-offset, edit inversed ray offset too;
-- [index] = {x, y, z, range}
ray_cast_offsets = {
    [1] = {0, 1.0, 0, 1.25},
    [2] = {0.225, 0.25, 0.225, 0.5},
    [3] = {0.225, 0.25, -0.225, 0.5},
    [4] = {-0.225, 0.25, 0.225, 0.5},
    [5] = {-0.225, 0.25, -0.225, 0.5},
}

function get_material(print)
    local pos = db.actor:position()
    local material
    local ray_hits = {}

    for k,v in pairs(ray_cast_offsets) do
        material = ray_cast(vector():set(pos.x + v[1], pos.y + v[2], pos.z + v[3]), vector():set(0, -1, 0), v[4], print)

        -- short circuit if centre ray hits water
        if k == 1 and water_materials[material] then return material end

        -- inversed ray cast to hit surfaces covered by fake geometry
        if fake_materials[material] then
            local inv_material = ray_cast(vector():set(pos.x, pos.y - 0.5, pos.z), vector():set(0, 1, 0), 0.5, print)
            if inv_material then material = inv_material end
        end

        -- select material with most hits
        if material then
            if not ray_hits[material] then
                ray_hits[material] = 1
            else
                ray_hits[material] = ray_hits[material] + 1
            end
        end
    end

    -- if print then
    --     for k,v in pairs(ray_hits) do
    --         print_dbg("raycast result: %s %s", k,v)
    --     end
    -- end

    local final_material = get_highest_value(ray_hits)
    if not final_material then
        -- backup horizontal plus-shaped ray cast
        final_material = ray_cast(vector():set(pos.x + 0.225, pos.y - 0.001, pos.z), vector():set(-1, 0, 0), 0.45, debug)
        if not final_material then
            final_material = ray_cast(vector():set(pos.x, pos.y - 0.001, pos.z + 0.225), vector():set(0, 0, -1), 0.45, debug)
        end
        print_dbg("backup material: %s", final_material)
    end

    return grass_patch and oleh_sound_utils.is_actually_grass and oleh_sound_utils.is_actually_grass(final_material) and "materials\\grass" or final_material
end

function on_option_change()
    if ui_mcm and ((oleh_sounds_mcm and oleh_sounds_mcm.on_mcm_load) or (extended_movement_sounds_mcm and extended_movement_sounds_mcm.on_mcm_load)) then
        enabled       = ui_mcm.get("oleh_sounds/movement/enabled_jump_sounds") or ui_mcm.get("extended_movement_sounds/enabled_jump_sounds")
        volume        = ui_mcm.get("oleh_sounds/movement/volume_jump_sounds") or ui_mcm.get("extended_movement_sounds/volume_jump_sounds") or 0.5
        servo_enabled = ui_mcm.get("oleh_sounds/movement/enabled_servo_sounds") or ui_mcm.get("extended_movement_sounds/enabled_servo_sounds")
        servo_volume  = ui_mcm.get("oleh_sounds/movement/volume_servo_sounds") or ui_mcm.get("extended_movement_sounds/volume_servo_sounds") or 0.5
        ice_patch     = ui_mcm.get("oleh_sounds/general/ice_patch") or ui_mcm.get("oleh_sounds/weapons/ice_patch") or ui_mcm.get("grok_casings_sounds/ice_patch")
        grass_patch = ui_mcm.get("oleh_sounds/general/grass_patch") or ui_mcm.get("extended_movement_sounds/grass_patch")
    end
end

function on_game_start()
    RegisterScriptCallback("actor_on_jump", actor_on_jump)
    RegisterScriptCallback("actor_on_land", actor_on_land)
    RegisterScriptCallback("on_option_change", on_option_change)
	on_option_change()

    --RegisterScriptCallback("actor_on_footstep", actor_on_footstep) -- uncomment to disable footsteps sounds
end

function actor_on_footstep(material, power, hud_view, flags)
    flags.ret_value = false
end

function print_dbg(txt, ...)
	if debug then
		printf("[eft_jump_sounds] " .. txt, ...)
	end
end

available_materials = {
    ["default"]                        = "dirt_",
    ["materials\\asphalt"]             = "concrete_", -- Асфальт
    ["materials\\bricks"]              = "concrete_", -- Кирпичная стена
    ["materials\\bush"]                = "grass_", -- Кусты, крона деревьев, камышы, листья 
    ["materials\\bush_sux"]            = "grass_", -- Кусты, крона деревьев, камышы, листья сухие
    ["materials\\cloth"]               = "dirt_", -- Ткань
    ["materials\\concrete"]            = "concrete_", -- Монолитный бетон
    ["materials\\death"]               = "dirt_", -- Смертоносная земля (нестандартный материал)
    ["materials\\dirt"]                = "dirt_", -- Мокрая грязь, болото 
    ["materials\\earth"]               = "dirt_", -- Сухая твердая земля (стандартный материал)
    ["materials\\earth_death"]         = "dirt_", -- Сухая твердая земля (нестандартный материал)
    ["materials\\earth_slide"]         = "dirt_", -- Сухая твердая земля (стандартный материал)
    ["materials\\flooring_tile"]       = "concrete_", -- Плитка, кафель
    ["materials\\glass"]               = "concrete_", -- Стекло
    ["materials\\grass"]               = "grass_", -- Земля, покрытая травой
    ["materials\\gravel"]              = "gravel_", -- Гравий
    ["materials\\metal"]               = "metal_", -- Монолитный метал, толстый кусок железа, танк
    ["materials\\metal_pipe"]          = "metal_", -- Металлическая труба
    ["materials\\metal_plate"]         = "metal_", --"metal_thin_", -- Металлическая пластина (толщина 2-5см), Ступеньки
    ["materials\\sand"]                = "gravel_", -- Песок, насыпь
    ["materials\\setka_rabica"]        = "metal_", -- Сетка рабица, колючая проволока
    ["materials\\shifer"]              = "concrete_", -- Шифер
    ["materials\\stucco"]              = "concrete_", -- штукатурка
    ["materials\\tin"]                 = "metal_", --"metal_thin_", -- Жесть, крыша домов
    ["materials\\tree_trunk"]          = "wood_", -- Дерево (ствол)
    ["materials\\water"]               = "water_", -- Вода
    ["materials\\water_radiation"]     = "water_", -- Вода
    ["materials\\wood"]                = "wood_", -- Деревянная поверхность, деревянный пол, деревянные ступеньки
    ["materials\\wooden_board"]        = "wood_", -- Деревянная доска (толщина 2-5см), деревянный вагон, ящик
    ["materials\\occ"]                 = "dirt_", -- Материал для оклюжен геометрии
    ["materials\\fake"]                = "dirt_", -- Материал для колижена (нет звука, следов от пуль, теней)
    ["materials\\fake_ladders"]        = "dirt_", -- невидимая лестница
    ["materials\\fake_ladders_woods"]  = "dirt_", -- невидимая деревянная лестница
    ["materials\\fake_slide"]          = "dirt_", -- Материал для колижена (нет звука, следов от пуль, теней)
}

fake_materials = {
    ["materials\\death"]               = true, -- Смертоносная земля (нестандартный материал)
    ["materials\\occ"]                 = true, -- Материал для оклюжен геометрии
    ["materials\\fake"]                = true, -- Материал для колижена (нет звука, следов от пуль, теней)
    ["materials\\fake_ladders"]        = true, -- невидимая лестница
    ["materials\\fake_ladders_woods"]  = true, -- невидимая деревянная лестница
    ["materials\\fake_slide"]          = true, -- Материал для колижена (нет звука, следов от пуль, теней)
}

water_materials = {
    ["materials\\water"]               = true,
    ["materials\\water_radiation"]     = true,
}