-- plays player footstep sounds - oleh5230, 17.08.25
-- Last edit: 12.05.25

local debug = false

local step_enabled = true
local step_volume = 0.5
local gear_enabled = true
local gear_volume = 0.5
local backpack_enabled = true
local backpack_volume = 0.5
local servo_enabled = true
local servo_volume = 0.5
local servo_legacy = false
local ice_patch = false
local grass_patch = false

local utils = oleh_sound_utils
local exo_path = servo_legacy and "exo_legacy\\servo_exo_walk_" or "exo\\servo_exo_walk_"

-- number of footstep sound files (samples) per class
limit = {
    ["crouch"] = 6,
    ["sprint"] = 6,
    ["walk"] = 6,

    ["cloth\\cloth_crouch"] = 9,
    ["cloth\\cloth_walk"] = 9,
    ["cloth\\cloth_sprint"] = 9,
    ["gear_rattle\\gear_rattle"] = 6,
    ["backpack\\backpack_rattle"] = 16,

    ["hand-0"] = 6,
    ["foot-0"] = 6,
}

function actor_on_footstep(material, power, hud_view, flags)
    -- footstep callback is being sent upon landing (sometimes even twice)
    if utils.land_tg + 200 > time_global() then return end

    --flags.ret_value = false -- uncomment to disable engine footstep sounds
    local move_state, volume = get_move_state()
    local _material = grass_patch and utils.is_actually_grass(material) and available_materials["materials\\grass"]
    or available_materials[material] or available_materials["default"]

    play_backpack_rattle(volume, move_state)
    play_exo_servo_sound(volume, move_state)

    play_cloth_sound(volume, move_state)
    play_gear_rattle(volume, move_state)

    if not step_enabled then return end

    if IsMoveState('mcClimb') and play_ladder_sound(_material, volume) then
    -- callback can't detect 'water_radiation' material, leave water steps to engine
    elseif _material ~= "water_" then
        play_footstep_sound(_material, volume, move_state)
    end
end

local last_fs = 0
function play_footstep_sound(material, volume, move_state)

    local roll = math.random(limit[move_state])
    if roll == last_fs then
        roll = last_fs % limit[move_state] + 1
    end
    last_fs = roll

    local sound = sound_object("footstep\\" .. material .. move_state .. roll)
    --printf("footstep_sounds: %s, volume: %s", "footstep\\" .. material .. move_state .. roll, volume * step_volume)
    sound:play(db.actor, 0, sound_object.s2d)
    sound.volume = volume * step_volume

end

local last_cl = 0
function play_cloth_sound(volume, move_state)
    if not gear_enabled then return end
    local cloth = "cloth\\cloth_" .. (move_state or "walk")

    local roll = math.random(limit[cloth])
    -- if roll == last_cl then
    --     roll = last_cl % (limit[cloth] + 1)
    -- end
    -- last_cl = roll

    local sound = sound_object(cloth .. roll)
    sound:play(db.actor, 0, sound_object.s2d)
    sound.volume = gear_volume * (volume or 1)
    --printf("%s, volume: %s", cloth .. roll, sound.volume)
end

local last_gr = 0
local gear = "gear_rattle\\gear_rattle"
function play_gear_rattle(volume, move_state)
    if not gear_enabled then return end

    local roll = math.random(limit[gear])
    -- if roll == last_gr then
    --     roll = last_gr % (limit[gear] + 1)
    -- end
    -- last_gr = roll

    local sound = sound_object(gear .. roll)
    sound:play(db.actor, 0, sound_object.s2d)
    sound.volume = gear_volume * 0.5 * (volume or 1)
    --printf("%s, volume: %s", gear .. roll, sound.volume)
end

local last_bp = 0
local backpack = "backpack\\backpack_rattle"
function play_backpack_rattle(volume, move_state)
    if not backpack_enabled then return end

    local roll = math.random(limit[backpack])
    -- if roll == last_bp then
    --     roll = last_bp % (limit[backpack] + 1)
    -- end
    -- last_bp = roll

    -- volume based on carry weight
    local weight = utils.total_weight or 10
    local max_weight = utils.max_weight or 60
    local weight_volume = clamp((weight/max_weight), 0, 1)
    if weight_volume < 0.3 then return end

    local sound = sound_object(backpack .. roll)
    sound:play(db.actor, 0, sound_object.s2d)
    sound.volume = weight_volume * backpack_volume * (volume or 1)
    --printf("%s, volume: %s, weight: %s, max_weight: %s", weight_volume, sound.volume, weight, max_weight)
end

local last_exo = false
function play_exo_servo_sound(volume, move_state)
    local exo_class = utils.exo_classes[utils.outfit.class]
    if servo_enabled and exo_class then
        local sound = sound_object(exo_path .. exo_class .. (last_exo and 2 or 1))
        sound:play(db.actor, 0, sound_object.s2d)
        sound.volume = servo_volume * (volume or 1)
        last_exo = not last_exo
    end
end

local raycast_count = 5
local part_count = false
function play_ladder_sound(material, volume)
    local ladder_material = ladder_fake_materials[material]
    -- cast ray to get ladder material (fake ladder materials are inconsistent)
    for i=1,raycast_count do
        local ray_material = ladder_materials[get_ladder_material(0.175 + i * 0.075, 0.15 + i * 0.075)]
        if ray_material then ladder_material = ray_material break end
    end
    if not ladder_material then return false end

    -- play foot/hand sound effect sequentially
    local part = part_count and "foot-0" or "hand-0"

    local step_snd = sound_object("ladder\\" .. ladder_material .. part .. math.random(limit[part]))
    step_snd:play(db.actor, 0, sound_object.s2d)
    step_snd.volume = step_volume * 3 * (volume or 1)
    part_count = not part_count

    -- play ladder rattle sound effect
    --local detail_snd = sound_object("ladder\\" .. ray_material .. "detail_" .. "1")
    --detail_snd:play(db.actor, 0, sound_object.s2d)
    --detail_snd.volume = step_volume * volume
    return true
end

function get_ladder_material(offset_x, offset_z)
    local pos = db.actor:position()
    local dir = db.actor:direction()

    -- offset position in the camera direction
    local offset_pos = vector():set(pos.x + dir.x * offset_x, pos.y + 0.5, pos.z + dir.z * offset_z)

    -- perpendicular direction using cross product with up vector
    local up = vector():set(0, 1, 0)
    local perpendicular = vector_cross(dir, up)
    perpendicular:normalize()

    local material = ray_cast(offset_pos, perpendicular, 1, debug)

    return material
end

-- in Swamps fake is used primarily for wood bridges
function actor_on_first_update()
    if level.name() == "k00_marsh" then
        available_materials["materials\\fake"] = "wood_plank_"
    else
        available_materials["materials\\fake"] = "dirt_"
    end
end

function get_move_state()
    local move_state = "walk"
    local accel_state = IsMoveState('mcAccel')
    local volume = 1

    if IsMoveState('mcSprint') then
        move_state = "sprint"
        volume = 1.7

    elseif IsMoveState('mcCrouch') then
        move_state = "walk"
        volume = 0.5
        if accel_state then
            move_state = "walk"
            volume = 0
        end

    elseif accel_state then
        move_state = "walk"
        volume = 0.3
    end

    -- if IsMoveState('mcClimb') then
    --     move_state = "climb_"
    --     volume = 1
    -- end

    return move_state, volume
end

function ray_cast(pos, dir, range, visualize)
    local ray = demonized_geometry_ray.geometry_ray({
        ray_range = range or 0.5,
        flags = 1 + 2 + 4 + 8,
        ignore_object = db.actor,
        visualize = visualize or false,
    })
    return ray:get(pos, dir).result.material_name
end

function load_settings()
    if ui_mcm and oleh_sounds_mcm and oleh_sounds_mcm.on_mcm_load then
        step_enabled        = ui_mcm.get("oleh_sounds/movement/enabled_footstep_sounds")
        step_volume         = ui_mcm.get("oleh_sounds/movement/volume_footstep_sounds") or 0.5
        gear_enabled        = ui_mcm.get("oleh_sounds/movement/enabled_gear_rustle_sounds")
        gear_volume         = ui_mcm.get("oleh_sounds/movement/volume_gear_rustle_sounds") or 0.5
        backpack_enabled    = ui_mcm.get("oleh_sounds/movement/enabled_backpack_rustle_sounds")
        backpack_volume     = ui_mcm.get("oleh_sounds/movement/volume_backpack_rustle_sounds") or 0.5
        servo_enabled       = ui_mcm.get("oleh_sounds/movement/enabled_servo_sounds")
        servo_volume        = ui_mcm.get("oleh_sounds/movement/volume_servo_sounds") or 0.5
        servo_legacy        = ui_mcm.get("oleh_sounds/movement/legacy_servo_sounds")

        ice_patch = ui_mcm.get("oleh_sounds/general/ice_patch") or ui_mcm.get("oleh_sounds/weapons/ice_patch")
        grass_patch = ui_mcm.get("oleh_sounds/general/grass_patch")
    elseif ui_mcm and extended_movement_sounds_mcm and extended_movement_sounds_mcm.on_mcm_load then
        step_enabled  = ui_mcm.get("extended_movement_sounds/enabled_footstep_sounds")
        step_volume   = ui_mcm.get("extended_movement_sounds/volume_footstep_sounds") or 0.5
        gear_enabled  = ui_mcm.get("extended_movement_sounds/enabled_gear_rustle_sounds")
        gear_volume   = ui_mcm.get("extended_movement_sounds/volume_gear_rustle_sounds") or 0.5
        servo_enabled = ui_mcm.get("extended_movement_sounds/enabled_servo_sounds")
        servo_volume  = ui_mcm.get("extended_movement_sounds/volume_servo_sounds") or 0.5

        ice_patch = ui_mcm.get("grok_casings_sounds/ice_patch")
        grass_patch = ui_mcm.get("extended_movement_sounds/grass_patch")
    end
    exo_path = servo_legacy and "exo_legacy\\servo_exo_walk_" or "exo\\servo_exo_walk_"
end

function on_game_start()
    assert(oleh_sound_utils and oleh_sound_utils.VERSION and oleh_sound_utils.VERSION >= 6, "\n\n"..
    "MovementSFX: oleh_sound_utils.script is missing or outdated, update MSIG (Miscellaneous Sound Improvements)\nhttps://github.com/oleh5230/MSIG")

    RegisterScriptCallback("actor_on_footstep", actor_on_footstep)
    RegisterScriptCallback("actor_on_first_update", actor_on_first_update)
    RegisterScriptCallback("on_option_change", load_settings)
    load_settings()
end

available_materials = {
    ["creatures\\actor"]               = "dirt_",

    ["default"]                        = "asphalt_", -- primarily used in Dead City
    ["materials\\asphalt"]             = "asphalt_", -- Асфальт
    ["materials\\bricks"]              = "asphalt_", -- Кирпичная стена
    ["materials\\bush"]                = "bush_", -- Кусты, крона деревьев, камышы, листья 
    ["materials\\bush_sux"]            = "bush_", -- Кусты, крона деревьев, камышы, листья сухие
    ["materials\\cloth"]               = "cloth_", -- Ткань
    ["materials\\concrete"]            = "asphalt_", -- Монолитный бетон
    ["materials\\death"]               = "dirt_", -- Смертоносная земля (нестандартный материал)
    ["materials\\dirt"]                = "dirt_", -- Мокрая грязь, болото 
    ["materials\\earth"]               = "dirt_", -- Сухая твердая земля (стандартный материал)
    ["materials\\earth_death"]         = "dirt_", -- Сухая твердая земля (нестандартный материал)
    ["materials\\earth_slide"]         = "dirt_", -- Сухая твердая земля (стандартный материал)
    ["materials\\flooring_tile"]       = "asphalt_", -- Плитка, кафель
    ["materials\\glass"]               = "asphalt_", -- Стекло
    ["materials\\grass"]               = "grass_", -- Земля, покрытая травой
    ["materials\\gravel"]              = "gravel_", -- Гравий
    ["materials\\metal"]               = "metal_solid_", -- Монолитный метал, толстый кусок железа, танк
    ["materials\\metal_pipe"]          = "metal_solid_", -- Металлическая труба
    ["materials\\metal_plate"]         = "metal_plate_", -- Металлическая пластина (толщина 2-5см), Ступеньки
    ["materials\\sand"]                = "gravel_", -- Песок, насыпь
    ["materials\\setka_rabica"]        = "metal_solid_", -- Сетка рабица, колючая проволока
    ["materials\\shifer"]              = "slate_", -- Шифер
    ["materials\\stucco"]              = "asphalt_", -- штукатурка
    ["materials\\tin"]                 = "metal_plate_", -- Жесть, крыша домов
    ["materials\\tree_trunk"]          = "wood_solid_", -- Дерево (ствол)
    ["materials\\water"]               = "water_", -- Вода
    ["materials\\water_radiation"]     = "water_", -- Вода
    ["materials\\wood"]                = "wood_plank_", -- Деревянная поверхность, деревянный пол, деревянные ступеньки
    ["materials\\wooden_board"]        = "wood_plank_", -- Деревянная доска (толщина 2-5см), деревянный вагон, ящик
    ["materials\\occ"]                 = "dirt_", -- Материал для оклюжен геометрии
    ["materials\\fake"]                = "dirt_", -- Материал для колижена (нет звука, следов от пуль, теней)
    ["materials\\fake_ladders"]        = "dirt_", -- невидимая лестница
    ["materials\\fake_ladders_woods"]  = "dirt_", -- невидимая деревянная лестница
    ["materials\\fake_slide"]          = "dirt_", -- Материал для колижена (нет звука, следов от пуль, теней)

    ["objects\\large_furniture"]       = "wood_", -- Red Forest tunnel planks
    ["objects\\large_metal_trash"]     = "metal_solid_", -- Limansk bridge
    ["objects\\dead_body"]             = "cloth_",
}

ladder_materials = {
    ["materials\\metal"]               = "metal_", -- Монолитный метал, толстый кусок железа, танк
    ["materials\\metal_pipe"]          = "metal_", -- Металлическая труба
    ["materials\\metal_plate"]         = "metal_", -- Металлическая пластина (толщина 2-5см), Ступеньки
    ["materials\\tin"]                 = "metal_", -- Жесть, крыша домов

    ["materials\\wood"]                = "wood_", -- Деревянная поверхность, деревянный пол, деревянные ступеньки
    ["materials\\wooden_board"]        = "wood_", -- Деревянная доска (толщина 2-5см), деревянный вагон, ящик
}

ladder_fake_materials = {
    ["materials\\fake_ladders"]        = "metal_", -- невидимая лестница
    ["materials\\fake_ladders_woods"]  = "wood_", -- невидимая деревянная лестница
}

function print_dbg(...)
	if debug then
		printf(...)
	end
end