-- plays player footstep sounds - oleh5230, 17.08.25
-- Last edit: 12.05.25

local debug = false

local step_enabled = true
local step_volume = 0.5
local gear_enabled = true
local gear_volume = 0.5
local servo_enabled = true
local servo_volume = 0.5
local servo_legacy = false
local ice_patch = false
local grass_patch = false

local utils = oleh_sound_utils
local exo_path = servo_legacy and "exo_legacy\\servo_exo_walk_" or "exo\\servo_exo_walk_"

-- extra sounds per outfit class
extra_sounds = {
    ["default"]             = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"},

    ["outfit_novice"]       = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"},
    ["outfit_light"]        = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"},
    ["outfit_medium"]       = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"},
    ["outfit_heavy"]        = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"},

    ["outfit_exo_proto"]    = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"}, -- "exo-gear-light\\light_sero_", 20
    ["outfit_exo"]          = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"}, --, "exo-gear-light\\light_sero_", 20
    ["outfit_exo_nosorog"]  = {"cloth\\cloth_", "gear_rattle\\gear_rattle_"}, --, "exo-gear-heavy\\heavy_servo_", 20
}

-- number of footstep sound files (samples) per move state
limit = {
    -- ["run_"] = 8,
    -- ["sprint_"] = 8,
    -- ["walk_"] = 6,
    -- ["prone_"] = 6,
    ["metal_hand-0"] = 6,
    ["metal_foot-0"] = 6,
    ["wood_hand-0"] = 6,
    ["wood_foot-0"] = 6,
    ["n_"] = 6,

    ["cloth\\cloth_"] = 6,
    ["gear_rattle\\gear_rattle_"] = 6,
    ["backpack\\backpack_rattle"] = 10
}

-- create sample queues to mitigate the issue of same sample playing multiple time in a row
queues = {}
count = {}
function init()
    for k,v in pairs(limit) do
        queues[k] = {}
        count[k] = 1
    end
    for k,v in pairs(queues) do
        for i=1, limit[k] do
            table.insert(queues[k], i)
        end
        shuffle_table(queues[k])
    end
end

function actor_on_footstep(material, power, hud_view, flags)
    -- footstep callback is being sent upon landing (sometimes even twice)
    if utils.land_tg + 200 > time_global() then return end

    --flags.ret_value = false -- uncomment to disable engine footstep sounds
    local move_state, volume = get_move_state()
    local _material = grass_patch and utils.is_actually_grass(material) and available_materials["materials\\grass"]
    or available_materials[material] or available_materials["default"]

    play_backpack_rattle(volume)
    play_exo_servo_sound(volume)

    if not step_enabled then return end
    play_cloth_sound(volume)
    play_gear_rattle(volume)

    if move_state == "climb_" and play_ladder_sound(_material, volume) then
    -- callback can't detect 'water_radiation' material, leave water steps to engine
    elseif _material ~= "water_" then
        play_footstep_sound(_material, volume)
    end
end

function play_footstep_sound(material, volume)
    local sound = sound_object("footstep\\" .. "n_" .. material .. queues["n_"][count["n_"]])
    --print_dbg("footstep_sounds: %s, volume: %s", "footstep\\" .. "n_" .. material .. queues["n_"][count["n_"]], volume * step_volume)
    sound:play(db.actor, 0, sound_object.s2d)
    sound.volume = volume * step_volume

    count["n_"] = count["n_"] + 1
    if count["n_"] > limit["n_"] then
        count["n_"] = 1
        shuffle_table(queues["n_"])
    end
end

function play_cloth_sound(volume)
    local cloth = extra_sounds[utils.outfit.class][1] or extra_sounds["default"]
    if cloth then
        local sound = sound_object(cloth .. queues[cloth][count[cloth]])
        sound:play(db.actor, 0, sound_object.s2d)
        sound.volume = step_volume * 0.5 * (volume or 1)
        --printf("%s, volume: %s", cloth .. queues[cloth][count[cloth]], sound.volume)

        count[cloth] = count[cloth] + 1
        if count[cloth] > limit[cloth] then
            count[cloth] = 1
            shuffle_table(queues[cloth])
        end
    end
end

function play_gear_rattle(volume)
    local gear = extra_sounds[utils.outfit.class][2] or extra_sounds["default"]
    if gear then
        local sound = sound_object(gear .. queues[gear][count[gear]])
        sound:play(db.actor, 0, sound_object.s2d)
        sound.volume = step_volume * 0.5 * (volume or 1)
        --printf("%s, volume: %s", gear .. queues[gear][count[gear]], sound.volume)

        count[gear] = count[gear] + 1
        if count[gear] > limit[gear] then
            count[gear] = 1
            shuffle_table(queues[gear])
        end
    end
end

function play_backpack_rattle(volume)
    if gear_enabled then
        -- volume based on carry weight, excluding outfit weight
        local backpack = "backpack\\backpack_rattle"
        local weight = utils.get_actor_total_weight() or 10
        local weight_volume = weight and utils.outfit.weight and clamp((weight - utils.outfit.weight)/100, 0.25, 1) or 1

        local sound = sound_object(backpack .. queues[backpack][count[backpack]])
        sound:play(db.actor, 0, sound_object.s3d)
        sound.volume = weight_volume * gear_volume * 0.2 * (volume or 1)

        count[backpack] = count[backpack] + 1
        if count[backpack] > limit[backpack] then
            count[backpack] = 1
            shuffle_table(queues[backpack])
        end
    end
end

local exo_count = true
function play_exo_servo_sound(volume)
    local exo_class = utils.exo_classes[utils.outfit.class]
    if servo_enabled and exo_class then
        local sound = sound_object(exo_path .. exo_class .. (exo_count and 2 or 1))
        sound:play(db.actor, 0, sound_object.s2d)
        sound.volume = servo_volume * (volume or 1)
        exo_count = not exo_count
    end
end

local raycast_count = 5
local part_count = false
function play_ladder_sound(material, volume)
    local ladder_material = ladder_fake_materials[material]
    -- cast ray to get ladder material (fake ladder materials are inconsistent)
    for i=1,raycast_count do
        local ray_material = ladder_materials[get_ladder_material(0.175 + i * 0.075, 0.15 + i * 0.075)]
        if ray_material then ladder_material = ray_material break end
    end
    if not ladder_material then return false end

    -- play foot/hand sound effect sequentially
    local part = part_count and "foot-0" or "hand-0"
    local class = ladder_material .. part

    local step_snd = sound_object("ladder\\" .. class .. queues[class][count[class]])
    step_snd:play(db.actor, 0, sound_object.s2d)
    step_snd.volume = step_volume * 2
    part_count = not part_count

    count[class] = count[class] + 1
    if count[class] > limit[class] then
        count[class] = 1
        shuffle_table(queues[class])
    end

    -- play ladder rattle sound effect
    --local detail_snd = sound_object("ladder\\" .. ray_material .. "detail_" .. "1")
    --detail_snd:play(db.actor, 0, sound_object.s2d)
    --detail_snd.volume = step_volume * volume
    return true
end

function get_ladder_material(offset_x, offset_z)
    local pos = db.actor:position()
    local dir = db.actor:direction()

    -- offset position in the camera direction
    local offset_pos = vector():set(pos.x + dir.x * offset_x, pos.y + 0.5, pos.z + dir.z * offset_z)

    -- perpendicular direction using cross product with up vector
    local up = vector():set(0, 1, 0)
    local perpendicular = vector_cross(dir, up)
    perpendicular:normalize()

    local material = ray_cast(offset_pos, perpendicular, 1, debug)

    return material
end

function get_move_state()
    local move_state = "n_"
    local accel_state = IsMoveState('mcAccel')
    local volume = 1

    if IsMoveState('mcSprint') then
        move_state = "sprint_"
        volume = 2

    elseif IsMoveState('mcCrouch') then
        move_state = "crouch_"
        volume = 0.5
        if accel_state then
            move_state = "prone_"
            volume = 0
        end

    elseif accel_state then
        move_state = "walk_"
        volume = 0.5
    end

    if IsMoveState('mcClimb') then
        move_state = "climb_"
        volume = 1
    end

    return move_state, volume
end

function ray_cast(pos, dir, range, visualize)
    local ray = demonized_geometry_ray.geometry_ray({
        ray_range = range or 0.5,
        flags = 1 + 2 + 4 + 8,
        ignore_object = db.actor,
        visualize = visualize or false,
    })
    return ray:get(pos, dir).result.material_name
end

function load_settings()
    if ui_mcm and oleh_sounds_mcm and oleh_sounds_mcm.on_mcm_load then
        step_enabled  = ui_mcm.get("oleh_sounds/movement/enabled_footstep_sounds")
        step_volume   = ui_mcm.get("oleh_sounds/movement/volume_footstep_sounds") or 0.5
        gear_enabled  = ui_mcm.get("oleh_sounds/movement/enabled_gear_rustle_sounds")
        gear_volume   = ui_mcm.get("oleh_sounds/movement/volume_gear_rustle_sounds") or 0.5
        servo_enabled = ui_mcm.get("oleh_sounds/movement/enabled_servo_sounds")
        servo_volume  = ui_mcm.get("oleh_sounds/movement/volume_servo_sounds") or 0.5
        servo_legacy  = ui_mcm.get("oleh_sounds/movement/legacy_servo_sounds")

        ice_patch = ui_mcm.get("oleh_sounds/general/ice_patch") or ui_mcm.get("oleh_sounds/weapons/ice_patch")
        grass_patch = ui_mcm.get("oleh_sounds/general/grass_patch")
    elseif ui_mcm and extended_movement_sounds_mcm and extended_movement_sounds_mcm.on_mcm_load then
        step_enabled  = ui_mcm.get("extended_movement_sounds/enabled_footstep_sounds")
        step_volume   = ui_mcm.get("extended_movement_sounds/volume_footstep_sounds") or 0.5
        gear_enabled  = ui_mcm.get("extended_movement_sounds/enabled_gear_rustle_sounds")
        gear_volume   = ui_mcm.get("extended_movement_sounds/volume_gear_rustle_sounds") or 0.5
        servo_enabled = ui_mcm.get("extended_movement_sounds/enabled_servo_sounds")
        servo_volume  = ui_mcm.get("extended_movement_sounds/volume_servo_sounds") or 0.5

        ice_patch = ui_mcm.get("grok_casings_sounds/ice_patch")
        grass_patch = ui_mcm.get("extended_movement_sounds/grass_patch")
    end
    exo_path = servo_legacy and "exo_legacy\\servo_exo_walk_" or "exo\\servo_exo_walk_"
end

function on_game_start()
    assert(oleh_sound_utils and oleh_sound_utils.VERSION and oleh_sound_utils.VERSION >= 5, "\n\n"..
    "MovementSFX: oleh_sound_utils.script is missing or outdated, update MSIG (Miscellaneous Sound Improvements)\nhttps://github.com/oleh5230/MSIG")

    RegisterScriptCallback("actor_on_footstep", actor_on_footstep)
    RegisterScriptCallback("on_option_change", load_settings)
    load_settings()
    init()
end

available_materials = {
    ["default"]                        = "default_",
    ["materials\\asphalt"]             = "concrete_", -- Асфальт
    ["materials\\bricks"]              = "tile_", -- Кирпичная стена
    ["materials\\bush"]                = "bush_", -- Кусты, крона деревьев, камышы, листья 
    ["materials\\bush_sux"]            = "bush_", -- Кусты, крона деревьев, камышы, листья сухие
    ["materials\\cloth"]               = "default_", -- Ткань
    ["materials\\concrete"]            = "tile_", -- Монолитный бетон
    ["materials\\death"]               = "earth_", -- Смертоносная земля (нестандартный материал)
    ["materials\\dirt"]                = "earth_", -- Мокрая грязь, болото 
    ["materials\\earth"]               = "earth_", -- Сухая твердая земля (стандартный материал)
    ["materials\\earth_death"]         = "earth_", -- Сухая твердая земля (нестандартный материал)
    ["materials\\earth_slide"]         = "earth_", -- Сухая твердая земля (стандартный материал)
    ["materials\\flooring_tile"]       = "tile_", -- Плитка, кафель
    ["materials\\glass"]               = "tile_", -- Стекло
    ["materials\\grass"]               = "grass_", -- Земля, покрытая травой
    ["materials\\gravel"]              = "gravel_", -- Гравий
    ["materials\\metal"]               = "metal_", -- Монолитный метал, толстый кусок железа, танк
    ["materials\\metal_pipe"]          = "metal_", -- Металлическая труба
    ["materials\\metal_plate"]         = "metal_plate_", -- Металлическая пластина (толщина 2-5см), Ступеньки
    ["materials\\sand"]                = "gravel_", -- Песок, насыпь
    ["materials\\setka_rabica"]        = "metal_", -- Сетка рабица, колючая проволока
    ["materials\\shifer"]              = "tile_", -- Шифер
    ["materials\\stucco"]              = "tile_", -- штукатурка
    ["materials\\tin"]                 = "metal_plate_", -- Жесть, крыша домов
    ["materials\\tree_trunk"]          = "wood_", -- Дерево (ствол)
    ["materials\\water"]               = "water_", -- Вода
    ["materials\\water_radiation"]     = "water_", -- Вода
    ["materials\\wood"]                = "wood_", -- Деревянная поверхность, деревянный пол, деревянные ступеньки
    ["materials\\wooden_board"]        = "wood_", -- Деревянная доска (толщина 2-5см), деревянный вагон, ящик
    ["materials\\occ"]                 = "wood_", -- Материал для оклюжен геометрии
    ["materials\\fake"]                = "default_", -- Материал для колижена (нет звука, следов от пуль, теней)
    ["materials\\fake_ladders"]        = "default_", -- невидимая лестница
    ["materials\\fake_ladders_woods"]  = "default_", -- невидимая деревянная лестница
    ["materials\\fake_slide"]          = "default_", -- Материал для колижена (нет звука, следов от пуль, теней)

    ["objects\\large_furniture"]       = "wood_", -- Red Forest tunnel planks
    ["objects\\large_metal_trash"]     = "metal_plate_", -- Limansk bridge
}

ladder_materials = {
    ["materials\\metal"]               = "metal_", -- Монолитный метал, толстый кусок железа, танк
    ["materials\\metal_pipe"]          = "metal_", -- Металлическая труба
    ["materials\\metal_plate"]         = "metal_", -- Металлическая пластина (толщина 2-5см), Ступеньки
    ["materials\\tin"]                 = "metal_", -- Жесть, крыша домов

    ["materials\\wood"]                = "wood_", -- Деревянная поверхность, деревянный пол, деревянные ступеньки
    ["materials\\wooden_board"]        = "wood_", -- Деревянная доска (толщина 2-5см), деревянный вагон, ящик
}

ladder_fake_materials = {
    ["materials\\fake_ladders"]        = "metal_", -- невидимая лестница
    ["materials\\fake_ladders_woods"]  = "wood_", -- невидимая деревянная лестница
}

function print_dbg(...)
	if debug then
		printf(...)
	end
end