FreelookActive = false
local freelook_toggle = false

land_tg = 0

function freelook_hold(key)
    local bind = dik_to_bind(key)
	if bind == key_bindings.kFREELOOK then
		FreelookActive = true
	end
end

function freelook_release(key)
    local bind = dik_to_bind(key)
	if bind == key_bindings.kFREELOOK then
		FreelookActive = false
	end
end

function load_settings()
    freelook_toggle = get_console_cmd(1,"g_freelook_toggle") or false
end

function actor_on_land()
    land_tg = time_global()
end

local cached_outfit = {
    id = nil,
    class = "default",
    weight = 10
}
function get_outfit_params()
    local item = db.actor:item_in_slot(7)
    if not item then return {id = nil,class = "default",weight = 1} end

    if item:id() ~= cached_outfit.id then
        local section = item:section()
        if not section then return end
        local outfit = {}
        outfit.weight = SYS_GetParam(2, section, "inv_weight", 10)
        outfit.class = SYS_GetParam(0, section, "repair_type", "default")

        if string.find(section, "proto") then
            outfit.class = "outfit_exo_proto"
        end

        if string.find(section, "nosorog") then
            outfit.class = "outfit_exo_nosorog"
        end

        outfit.id = item:id()
        --printf("%s %s %s" , outfit.id, outfit.class, outfit.weight)
        cached_outfit = outfit
    end

    return cached_outfit
end

local cached_actor_total_weight = 0
function get_actor_total_weight()
    return cached_actor_total_weight
end

function actor_on_item_moved()
    cached_actor_total_weight = db.actor:get_total_weight()
end

-- legacy method
local cached_outfit_id = nil
local cached_outfit_class = "default"
function get_outfit_class()
    local outfit = db.actor:item_in_slot(7)
    if not outfit then return "default" end

    if outfit:id() ~= cached_outfit_id then
        local section = outfit:section()
        if not section then return end
        local outfit_class = SYS_GetParam(0, section, "repair_type") or "default"

        if string.find(section, "proto") then
            outfit_class = "outfit_exo_proto"
        end

        if string.find(section, "nosorog") then
            outfit_class = "outfit_exo_nosorog"
        end

        cached_outfit_class = outfit_class
        cached_outfit_id = outfit:id()
    end

    return cached_outfit_class
end

burn_tg = 0
no_grass_near_anomaly_levels = {
    ["zaton"]       = true,
    ["jupiter"]     = true,
    ["pripyat"]     = true,
}

function actor_on_before_hit(shit, bone_id, flags)
    if shit.type == hit.burn then
        burn_tg = time_global()
    end
end

-- some levels use 'earth' material for grassy terrain
-- horrendous levels like Dead City are beyond repair
function is_actually_grass(material)
    if material == "materials\\earth"
    -- no grass underground/indoors
    and level.rain_hemi() > 0.25 then
        -- no grass near some thermal anomalies
        if no_grass_near_anomaly_levels[level.name()] and (time_global() < burn_tg + 1000) then
        else
            return true
        end
    end
    return false
end

function on_game_start()
    RegisterScriptCallback("on_key_hold", freelook_hold)
    RegisterScriptCallback("on_key_release", freelook_release)

    RegisterScriptCallback("actor_on_land", actor_on_land)

    RegisterScriptCallback("actor_on_item_drop", actor_on_item_moved)
    RegisterScriptCallback("actor_item_to_ruck", actor_on_item_moved)

    RegisterScriptCallback("actor_on_before_hit", actor_on_before_hit)

    RegisterScriptCallback("on_option_change", load_settings)
    RegisterScriptCallback("on_console_execute", load_settings)
    load_settings()
end